<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "jct_json_ld"
 *
 * Auto generated by Extension Builder 2018-07-03
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'JSON-LD Generator',
    'description' => 'A simple and interactive JSON-LD Generator',
    'category' => 'module',
    'author' => 'Jérémie Constant',
    'author_email' => 'mail@jeremieconstant.de',
    'state' => 'alpha',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '0.0.1',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
